services:
  - type: web
    name: dts-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    disk:
      name: dts-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 3001
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM_NAME
        sync: false
